import Head from "next/head";

function HeadTag({ title }) {
  return (
    <Head>
      <title>{title} | LinkedIn Clone</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
  );
}

export default HeadTag;
